# Generated by Django 3.2.4 on 2021-07-11 00:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0004_rename_adress_shippingadress_address'),
    ]

    operations = [
        migrations.RenameField(
            model_name='shippingadress',
            old_name='sate',
            new_name='state',
        ),
    ]
